name: CMake

on:
  [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-20.04, macos-latest, macos-11 ]
    runs-on: ${{ matrix.os }}
    env:
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
      HOMEBREW_NO_INSTALL_UPGRADE: 1
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install packaged dependencies
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then sudo apt-get update; fi
        if [[ "$RUNNER_OS" == "Linux" ]]; then sudo apt-get install libliquid-dev libglib2.0-dev libfftw3-dev libsoapysdr-dev libconfig++-dev; fi
        if [[ "$RUNNER_OS" == "macOS" ]]; then brew update; fi
        if [[ "$RUNNER_OS" == "macOS" ]]; then brew install glib liquid-dsp fftw soapysdr libconfig; fi

    - name: Install libacars
      run: |
        cd "$RUNNER_TEMP"
        git clone https://github.com/szpajder/libacars.git
        cd libacars
        mkdir build
        cd build
        cmake ..
        make -j
        sudo make install
        if [[ "$RUNNER_OS" == "Linux" ]]; then sudo ldconfig; fi
        if [[ "$RUNNER_OS" == "macOS" ]]; then sudo update_dyld_shared_cache; fi

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Install
      run: sudo cmake --install ${{github.workspace}}/build

    - name: Test run
      run: /usr/local/bin/dumphfdl --help
